# Generated by Django 2.2.6 on 2019-10-11 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.IntegerField(primary_key=True, serialize=False)),
                ('number_of_episodes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HotSauce',
            fields=[
                ('hotsauce_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('scoville_units', models.IntegerField()),
                ('seasons', models.ManyToManyField(to='api.Season')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('episode_id', models.IntegerField(primary_key=True, serialize=False)),
                ('guest', models.CharField(max_length=100)),
                ('episode_in_season', models.IntegerField()),
                ('title', models.TextField(default='')),
                ('link', models.URLField(default='')),
                ('completed', models.BooleanField(default=True)),
                ('dab', models.BooleanField(default=True)),
                ('vegan', models.BooleanField(default=False)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Season')),
            ],
        ),
    ]
