# Generated by Django 2.2.6 on 2019-10-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotsauce',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
